### ISSUE TITLE
Remove extract-text-webpack-plugin in favor of mini-css-extract-plugin

### ISSUE THREAD

**Issue by rinti** [Frojd/react-sass-starterkit#19]
According to the readme at [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin), the extract text plugin is now deprecated for use with CSS.
We should use the recommended [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) instead.

**Comment by iksototh** [comment]
This is now fixed in the latest release
