### ISSUE TITLE
Make it possible to override the preview template on component basis

### ISSUE THREAD

**Issue by marteinn** [Frojd/react-sass-starterkit#3]
My suggestion:
- Drop the current snippet override
- Use the MyComponent.html template and use that markup instead of the server generated markup

**Comment by marteinn** [comment]
References:
- https://github.com/marteinn/Delicious-Elixir/blob/develop/frontend/bin/server.js#L172
- https://github.com/marteinn/Delicious-Elixir/blob/develop/frontend/app/index.js#L18

**Comment by danielfrojd** [comment]
This is now fixed in 1.4.0 where you can add a complete override on component basis:
[Readme entry](https://github.com/Frojd/react-sass-starterkit#full-component-override)
