### ISSUE TITLE
Possibility to add components to different entry files

### ISSUE THREAD

**Issue by rinti** [Frojd/react-sass-starterkit#7]
This would be useful when needing to have different react projects within a project.

Basically an argument to `new Component` command like `npm run new Component --entry=SomeEntry` would look in webpack.config.js after config.entry.SomeEntry and run the command on that js-file instead of the hardcoded index.js.

**Comment by rinti** [comment]
As an easy workaround when needing this simply replace `index.js` with `your-index.js` in `internals/cli/updateIndexJs`.

**Comment by iksototh** [comment]
Will close this issue now as in the later versions there is support for multiple folders (althou some manual work to start a new componentsfolder is needed). 
For multiple projectes/themeing I would suggest having the frontend package next to eachother instead, like:
frontend/project1/
frontend/project2/
